(function(){'use strict';
 const cfg=window.ARK_DASHBOARD_CONFIG,$=id=>document.getElementById(id),DAY=86400000,iso=n=>new Date(n).toISOString().slice(0,10);
 let token='',preset='today',ticket=0,syncing=false,report=null,lastAccess=0;
 let storage;try{storage=sessionStorage;}catch{storage={getItem(){},setItem(){},removeItem(){}};}
 const safe=n=>Number.isSafeInteger(n)&&n>=0, count=n=>new Intl.NumberFormat('en-US').format(n), date=s=>new Date(s).toLocaleString('en-GB',{timeZone:'UTC'});
 function range(){let end=$('end').value,start=$('start').value,today=iso(Date.now());if(preset!=='custom'){end=today;start=preset==='all'?cfg.launchDate:preset==='today'?today:iso(Date.parse(today)-(Number(preset)-1)*DAY);}if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||iso(Date.parse(start))!==start||iso(Date.parse(end))!==end||start>end||end>today||end<cfg.launchDate||Date.parse(end)-Date.parse(start)>3660*DAY)throw Error('Choose a valid date range.');start=start<cfg.launchDate?cfg.launchDate:start;return {start,end:iso(Date.parse(end)+DAY),displayEnd:end};}
 async function request(body,ms=10000){const r=await fetch(cfg.endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:cfg.publicKey,Authorization:'Bearer '+cfg.publicKey,'x-ark-dashboard-code':token},body:JSON.stringify({...body,version:4}),signal:AbortSignal.timeout(ms),cache:'no-store'});if(r.status===401)throw Error('Access code not recognized.');if(!r.ok)throw Error('Reporting is temporarily unavailable.');const raw=await r.text();if(raw.length>2000000)throw Error('Report exceeds limit.');return JSON.parse(raw);}
 function validate(d,r){if(d.version!==4||d.start!==r.start||d.end!==r.end||!Number.isFinite(Date.parse(d.updated_at))||!Array.isArray(d.popups)||d.popups.length!==2||new Set(d.popups.map(p=>p.popup)).size!==2||!Array.isArray(d.daily)||d.daily.length>3661)throw Error('Report does not match this period.');for(const stamp of ['data_from','data_through','delivery_through','sales_through'])if(d[stamp]!==null&&(!Number.isFinite(Date.parse(d[stamp]))||Date.parse(d[stamp])>Date.parse(d.updated_at)))throw Error('Invalid reporting coverage.');for(const n of ['views','accepted','email','sms','email_delivered','sms_delivered'])if(!safe(d.totals?.[n]))throw Error('Invalid report counts.');for(const p of d.popups){if(!['p1','p2'].includes(p.popup))throw Error('Invalid popup.');for(const n of ['views','accepted','email','sms','email_delivered','sms_delivered'])if(!safe(p[n]))throw Error('Invalid popup counts.');}for(const day of d.daily)if(day.date<r.start||day.date>=r.end||!safe(day.email))throw Error('Invalid daily result.');return d;}
 function render(d,r,cached=false){const hasData=Number.isFinite(Date.parse(d.data_from))&&Math.min(Date.parse(d.data_through),Date.parse(r.end))>Date.parse(d.data_from);window.ARKDashboardUI.render(d,r);report=d;lastAccess=Date.now();$('error').textContent='';$('details').hidden=true;$('details').replaceChildren();$('period').textContent=r.start+' – '+r.displayEnd+' · UTC';$('badge').textContent=d.sync_paused?'Sync paused':!hasData?'No verified period':cached||Date.now()-Date.parse(d.data_through)>20*60000?'Saved data':'Updated';$('views').textContent=hasData&&d.telemetry_at?count(d.totals.views):'—';$('email').textContent=hasData?count(d.totals.email):'—';$('sms').textContent=hasData?count(d.totals.sms):'—';$('rate').textContent=!d.partial_telemetry&&d.totals.views&&hasData&&d.totals.email<=d.totals.views?(d.totals.email/d.totals.views*100).toFixed(1)+'%':'—';
 $('coverage').textContent=!hasData?'No tracked data overlaps this period.':d.range_clipped?'Showing available tracking from '+date(d.data_from)+' UTC. All counts and conversion use this same window; earlier days are not included.':'Counts and conversion cover the same tracked period. Browser blocking can still prevent some events.';
 $('freshness').textContent=(cached?'Saved report · ':'')+'Views & signups through '+(hasData?date(d.data_through)+' UTC':'not available for this period')+' · Background refresh every 5 minutes';
 if(!hasData)$('error').textContent='No fully synchronized signup window is available for these dates yet. Previous date ranges remain available.';
 $('delivery').textContent=hasData&&Date.parse(d.delivery_through)>=Math.min(Date.parse(d.data_through),Date.parse(d.end))?`${d.totals.email_delivered} of ${d.totals.email} received welcome email · ${d.totals.sms_delivered} of ${d.totals.sms} received welcome SMS`:'Delivery history verified through '+(d.delivery_through?date(d.delivery_through)+' UTC':'not yet')+'. Signup figures above are independently verified.';
 $('rows').replaceChildren();for(const p of d.popups){const tr=document.createElement('tr'),td=document.createElement('td'),b=document.createElement('button');b.className='button';b.textContent=p.popup==='p1'?'ARK Melts':'Leaving already';b.onclick=()=>window.ARKDashboardUI.openPopup(p.popup);td.append(b);tr.append(td);for(const n of ['views','accepted','email','sms']){const c=document.createElement('td');c.textContent=!hasData||((n==='views'||n==='accepted')&&!d.telemetry_at)?'—':count(p[n]);tr.append(c);}const cv=document.createElement('td');cv.textContent=!d.partial_telemetry&&p.views&&p.accepted<=p.views?(p.accepted/p.views*100).toFixed(1)+'%':'—';tr.append(cv);const er=document.createElement('td');er.textContent=!d.partial_telemetry&&hasData&&p.views&&p.email<=p.views?(p.email/p.views*100).toFixed(1)+'%':'—';tr.append(er);$('rows').append(tr);}
 $('trend').closest('.chart-area').hidden=!hasData;
 const vals=hasData?d.daily.filter(x=>Date.parse(x.date)<Date.parse(d.data_through)&&Date.parse(x.date)+DAY>Date.parse(d.data_from)).map(x=>x.email):[],max=Math.max(1,...vals),xy=vals.map((n,i)=>[vals.length===1?500:i/(vals.length-1)*1000,150-n/max*138]);$('trend').setAttribute('d',xy.map((p,i)=>(i?'L':'M')+p.join(',')).join(' '));$('point').style.display=xy.length===1?'':'none';if(xy.length){$('point').setAttribute('cx',xy[0][0]);$('point').setAttribute('cy',xy[0][1]);}$('chartTitle').textContent='Daily verified email signups, '+r.start+' to '+r.displayEnd;$('chartStart').textContent=r.start;$('chartEnd').textContent=r.displayEnd;
 $('sales').textContent=!hasData||!d.sales_through||Date.parse(d.sales_through)<Math.min(Date.parse(d.data_through),Date.parse(d.end))?'Order history verified through '+(d.sales_through?date(d.sales_through)+' UTC':'not yet')+'.':d.post_signup_sales?.length?d.post_signup_sales.map(x=>`${x.orders} order(s) · ${Number(x.value).toFixed(2)} ${x.currency}`).join(' / '):'No qualifying orders recorded in the selected signup cohort.';
 $('setup').textContent='Launch: '+date(d.launch_at)+' UTC. Tracking: '+(d.telemetry_at?date(d.telemetry_at)+' UTC':'not connected')+'.';if(d.sync_paused||d.sync_error||!d.background_enabled)$('error').textContent='Provider sync needs attention. Saved numbers remain visible; no failed refresh is shown as zero.';
 }
 function showDetails(id){$('details').hidden=false;$('details').replaceChildren();const title=document.createElement('p');title.textContent=(id==='p1'?'Product':'Exit')+' popup · versions observed in this period';$('details').append(title);for(const v of (report.versions||[]).filter(x=>x.popup===id)){const p=document.createElement('p');p.textContent=`${v.form_version} · ${v.views} views · ${v.accepted} accepted requests · last seen ${date(v.last_seen)} UTC`;$('details').append(p);}if(!(report.versions||[]).some(x=>x.popup===id)){const p=document.createElement('p');p.textContent='No tracked version events yet. Earlier signup history is retained separately.';$('details').append(p);}}
 async function load(){const my=++ticket;let r;try{r=range();}catch(e){$('error').textContent=e.message;return;}const key='ark-popup-report-v7:'+r.start+':'+r.end;try{const raw=storage.getItem(key);if(raw&&raw.length<2000000)render(validate(JSON.parse(raw),r),r,true);}catch{}try{const d=validate(await request({action:'report',start:r.start,end:r.end}),r);if(my!==ticket)return;render(d,r);try{storage.setItem(key,JSON.stringify(d));const keys=Object.keys(storage).filter(k=>k.startsWith('ark-popup-report-v7:'));for(const k of keys.slice(0,Math.max(0,keys.length-24)))storage.removeItem(k);}catch{}}catch(e){if(my===ticket)$('error').textContent=e.message+' Saved results, if shown, are unchanged.';}}
 async function refresh(){if(syncing)return;syncing=true;$('refresh').disabled=true;try{await load();}finally{syncing=false;$('refresh').disabled=false;}}
 $('lockForm').onsubmit=async e=>{e.preventDefault();token=$('code').value.trim();$('lockError').textContent='Checking…';try{const r=range();const d=validate(await request({action:'report',start:r.start,end:r.end}),r);$('lock').hidden=true;document.body.classList.remove('locked');$('code').value='';render(d,r);}catch(e){token='';$('lockError').textContent=e.message;}};
 $('logout').onclick=()=>{token='';ticket++;report=null;for(const k of Object.keys(storage))if(k.startsWith('ark-popup-report-v7:'))storage.removeItem(k);location.reload();};
 $('refresh').onclick=refresh;$('custom').onsubmit=e=>{e.preventDefault();load();};$('presets').onclick=e=>{const b=e.target.closest('[data-range]');if(!b)return;preset=b.dataset.range;for(const x of $('presets').querySelectorAll('button'))x.setAttribute('aria-pressed',String(x===b));$('custom').hidden=preset!=='custom';if(preset!=='custom')load();};window.addEventListener('focus',()=>{if(token&&Date.now()-lastAccess>60000){load();}});
 $('start').value=cfg.launchDate;$('end').value=iso(Date.now());$('start').max=$('end').max=iso(Date.now());
})();
